# Generated by Django 3.2.3 on 2021-06-09 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0002_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact Us'},
        ),
    ]
