# Generated by Django 3.2.2 on 2021-05-12 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=100)),
                ('phone', models.PositiveBigIntegerField(blank=True, null=True)),
                ('profice_pic', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('qualification', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainer.qualification')),
            ],
        ),
    ]
