# Generated by Django 3.2.3 on 2021-06-16 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion_comment',
            name='parent',
        ),
    ]
