# Generated by Django 3.2.3 on 2021-05-23 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
