# Generated by Django 3.2.3 on 2021-05-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_post_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(default='assignment', max_length=100),
            preserve_default=False,
        ),
    ]
