# Generated by Django 3.2.3 on 2021-06-04 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0001_initial'),
        ('courses', '0005_post_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('assiment_name', models.CharField(max_length=256)),
                ('grading', models.CharField(max_length=10)),
                ('file', models.FileField(upload_to=None)),
                ('marks', models.IntegerField()),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.batch')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainee.student')),
            ],
        ),
    ]
