# Generated by Django 3.2.3 on 2021-06-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_grade_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assignments'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grading',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
